### ISSUE TITLE
zk 路径问题

### ISSUE THREAD

**Issue by chennqqi** [meitu/go-consumergroup#23]
如果使用了自己定义的路径，怎么解决，在zk_grou_stroage中固定了这些位置
const (
	ownerPath     = "/consumers/%s/owners/%s/%d"
	consumersDir  = "/consumers/%s/ids"
	consumersPath = "/consumers/%s/ids/%s"
	offsetsPath   = "/consumers/%s/offsets/%s/%d"
	brokersDir    = "/brokers/ids"
	brokersPath   = "/brokers/ids/%s"
)

如果kafka的资源位于自定义路径下,特别是zk是公共zk，怎么处理
例如/zk_kafka/consumers%s/owners...

**Comment by git-hulk** [comment]
这个是 go-zookeeper 不支持 chroot 的问题，这个我们也提过 pr 给 go-zookeeper,  不过开发者似乎不太接受这个东西，所以我们自己包了一个 https://github.com/meitu/zk_wrapper， 只是还没加入到 go-consumergroup 里面来，这个我看看今天可以来支持一下

**Comment by git-hulk** [comment]
@chennqqi 没问题，这个本来也打算支持，理论上 chroot 在go-zookeeper 做会更加合适一些。目前为止不太可能，今天会支持并测试，有其他问题欢迎反馈 :)

**Comment by chennqqi** [comment]
Thank you!

**Comment by git-hulk** [comment]
@chennqqi 已支持，请更新到最新代码后通过在 config 里面增加 Chroot 配置即可

**Comment by chennqqi** [comment]
多谢，我在我的环境测试一下
