### ISSUE TITLE
问一下，启动了两个consumergroup进程接收消息

### ISSUE THREAD

**Issue by lycclsltt** [meitu/go-consumergroup#26]
问一下，启动了两个consumergroup进程接收消息，消息只打到一个进程里，另一个进程没有任何消息，这是什么原因，怎么才能把消息平均到两个consumer进程里

**Comment by lycclsltt** [comment]
今天我测试了下，和你描述的一致。查看了下，因为只有一个partition, 我通过kafka命令行工具给topic创建了多个partition后两个consumer都能收到消息了，有一点觉得不太好就是只有一个partition时，另一个是backup, 不能像rabbitmq一样同时消费。

**Comment by git-hulk** [comment]
@lycclsltt 这个是 partition 设计问题, 问题解决了我关闭这个 issue
